### ISSUE TITLE
Critical : Secondary Display issue in Android Oreo

### ISSUE THREAD

**Issue by sarathrda** [LogmeinRescue/Android-SDK#17]
In Android Oreo devices, one the `DeviceScreenStreaming` is started, the app exits with a toast as `This app does not support launch on secondary displays`. 

**STEPS TO REPRODUCE**

- Create a new Standard session using PIN Code
- Initiate the session in the Android app in Oreo OS device
- Accept the incoming request in the Technician console
- Click on `Start Now` in the Android App to start the Device screen streaming
- Observe that the above toast is displayed and the app is closed in the device
- But the app screen is being streamed live in the Technician console, while in the device, the user is able to access other apps.
- Until the PocketGeek app is launched, the streaming is not live.

Also inconsistently, we are noticing that the device screen is magnified in the Technician console as well.

We assume that this is because of the Multi Display support in Android Oreo as said [here](https://developer.android.com/about/versions/oreo/android-8.0#mds).

Please let us know, how to address the issue.

**Comment by balazsbanyai** [comment]
Hello, 

We've tried to reproduce the issue with the device screen streaming demo application on both emulators and physical devices, with no luck. We also enabled simulation of secondary displays, but the isse still didn't show. When we click on the `Start now` button on the devices, the streaming always starts, and we could not observe the toast that you mentioned. 

Did you experience this issue with the demo application, or your own app?
Could you let us know what kind of device have you been testing with?
Regarding the "magnification", could you attach a screenshot?

Thank you very much, Balazs

**Comment by sarathrda** [comment]
Hello,

We have been noticing this behaviour in our Application. 

We tested it in the following device:
Device Model: **Google Pixel**
OS Version: **Android Oreo(8.1.0)**

Regarding `magnification`, we have noticed it  few times at the Initial stages, but then we didn't notice it. We will update you with a screenshot, if we come across the scenario.

Thanks.

**Comment by balazsbanyai** [comment]
Hello,

Thank you for the information. Could you go ahead and try to reproduce it
with the demo app? If you succeed, please describe the reproduction steps,
so we can test it as well.

Could you tell us the target api level of the embedder app?

Balazs

**Comment by balazsbanyai** [comment]
Hi,

Now I get your point. We're terribly sorry about this, as the issue lies in the insufficient documentation of the SDK. I'll leave this issue open until we resolve that, and in the meanwhile, I can offer two workarounds:

### Option 1:
- Add the deviceinfo extension to the classpath of your application (`implementation("com.logmein.rescuesdk:deviceinfo:${rescuesdkVersion}@aar")`), 
- Use the extension in your app, using the `sessionFactory.useExtension(DeviceInfoExtension.class)`
This will cause the technican console to show the tab with the detailed device info and the remote view window.

### Option 2
- Open the Rescue Administration center
- Select the target technician group on the left hand side
- Select the organization tab
- Ensure that the `Classic display for mobile` option is ticked
This way, the only tab that will show up in the technician console will be the dedicated remote view tab, where the technician can initiate the remote viewing session, without any device info.

Please let us know if we can assist any further.

**Comment by sarathrda** [comment]
Hello Balazs,

Are the above solutions recommedned for the `Device Streaming` issue in the `LogMeIn Demo` app? Or `Android Oreo` issue?

Thanks

**Comment by balazsbanyai** [comment]
Any of these should result in the proper functionality of the demoapp, so
you can proceed with trying to reproduce the original issue using the demo
app.

Your help is much appreciated, Balazs

**Comment by balazsbanyai** [comment]
As we discussed earlier, we suggest to make your application non-resizable explicitly by using the `android:resizableActivity` on your `<application>`. 
This requirement will be added to the documentation of the SDK. In case you do need your app to be resizable, please open a separate issue.
