### ISSUE TITLE
3.6.0 SDK incompatible with okhttp 4.x.x

### ISSUE THREAD

**Issue by daravenph** [LogmeinRescue/Android-SDK#47]
I'm integrating the logMeIn SDK into an app which has a transitive dependency to okHttp 4.x.x. It is failing when trying to establish connectiton:

Caused by: java.lang.NoSuchMethodError: No static method get(Ljavax/net/ssl/X509TrustManager;)Lokhttp3/internal/tls/CertificateChainCleaner; in class Lokhttp3/internal/tls/CertificateChainCleaner;

I believe the issue is due to the migration of OkHttp to kotlin and the usage of Companion object. It should follow the format: CertificateChainCleaner.Companion.

https://square.github.io/okhttp/upgrading_to_okhttp_4/

Will there be an SDK release to support okhttp 4.x.x

**Comment by tamasgyongyosi** [comment]
Hi @daravenph ,

Thank you for this question. There will be an SDK release to support okhttp 4 in the near future but there is no timeline yet. I will let you know if there will be an exact date for this.

Best, Tamás

**Comment by yurishevtsov** [comment]
Hi @tamasgyongyosi,

Is there any update on the timeline for the okhttp 4.x.x support? We are still seeing this issue in SDK release 6.7.2.

**Comment by cswagner** [comment]
Hi @tamasgyongyosi,

I just want to check in on the status of this. We need to update okhttp to 4.x.x in order to target Android 11 in our app. However, given the incompatibility, this crash is blocking our ability to target Android 11. Starting this August, apps must target Android 11 (see [here](https://developer.android.com/distribute/best-practices/develop/target-sdk)).

**Comment by tamasgyongyosi** [comment]
Hi guys,

@yurishevtsov Sorry but I have no timeline for that comatibility yet.

@cswagner AFAIK okhttp 4.x.x is not required for targeting android 11. Why do you need it? Our application uses this SDK and targets android 11 too.

**Comment by cswagner** [comment]
My mistake @tamasgyongyosi; we had a related issue with Android 11, but we're able to workaround it.

However, we are running into this crash again due to a mismatch between the okhttp version used in v3.7.2 of this SDK and the okhttp version of another one of our dependencies.

Is there any update on the timeline for support of okhttp 4.x.x?

**Comment by tamasgyongyosi** [comment]
Hi @daravenph and @cswagner ,

We've released the 3.8.0 version of SDK with OKHTTP 4 compatibility. Please make sure it works in your applications.

**Comment by cswagner** [comment]
This is working on our end. Thanks!

**Comment by tamasgyongyosi** [comment]
I'm glad it works. Thanks for your feedback.
